### ISSUE TITLE
Validate downloads with cheksums

### ISSUE THREAD

**Issue by rgreinho** [PeopleForBikes/brokenspoke-analyzer#238]
# Feature request

When possible it would be nice to validate the downloads with their checksums.

## Current Behavior

The files are just downloaded and written on disk. There is no validation.

## Expected Behavior

Once the download is complete, we could use the checksum file to ensure that it did not get corrupted.

## Possible Solution

For example, for Geofabrik, they provide checksums for their file: https://download.geofabrik.de/north-america/us.html

**Comment by lalver1** [comment]
It would also be good to validate gzip downloads (such as the LODES data) since there have been several times when the downloaded `.csv.gz`is not valid. If the downloaded file is invalid (but exists in the folder) the `compute` command will produce an `Aborted` error.
